// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rbac/app/model/internal"
)

// TbMenu is the golang structure for table tb_menu.
type TbMenu internal.TbMenu

// Fill with you ideas below.