// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rbac/app/model/internal"
)

// TbRole is the golang structure for table tb_role.
type TbRole internal.TbRole

// Fill with you ideas below.