// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rbac/app/model/internal"
)

// TbRoleMenu is the golang structure for table tb_role_menu.
type TbRoleMenu internal.TbRoleMenu

// Fill with you ideas below.