// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rbac/app/model/internal"
)

// TbUserRole is the golang structure for table tb_user_role.
type TbUserRole internal.TbUserRole

// Fill with you ideas below.