// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rbac/app/model/internal"
)

// TbUser is the golang structure for table tb_user.
type TbUser internal.TbUser

// Fill with you ideas below.