// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// TbMenu is the golang structure for table tb_menu.
type TbMenu struct {
    Id       int64       `orm:"id,primary" json:"id"`        // 主键                                                         
    Name     string      `orm:"name"       json:"name"`      // 名称                                                         
    MenuCode string      `orm:"menu_code"  json:"menu_code"` // 菜单编码                                                     
    ParentId int64       `orm:"parent_id"  json:"parent_id"` // 父节点                                                       
    NodeType int         `orm:"node_type"  json:"node_type"` // 节点类型，1文件夹，2页面，3按钮                              
    IconUrl  string      `orm:"icon_url"   json:"icon_url"`  // 图标地址                                                     
    Sort     int         `orm:"sort"       json:"sort"`      // 排序号                                                       
    LinkUrl  string      `orm:"link_url"   json:"link_url"`  // 页面对应的地址                                               
    Level    int         `orm:"level"      json:"level"`     // 层次                                                         
    Path     string      `orm:"path"       json:"path"`      // 树id的路径 整个层次上的路径id，逗号分隔，想要找父节点特别快  
    IsDelete int         `orm:"is_delete"  json:"is_delete"` // 是否删除 1：已删除；0：未删除                                
    CreateAt *gtime.Time `orm:"create_at"  json:"create_at"` //                                                              
    UpdateAt *gtime.Time `orm:"update_at"  json:"update_at"` //                                                              
}