// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// TbRoleMenu is the golang structure for table tb_role_menu.
type TbRoleMenu struct {
    Id       uint64      `orm:"id,primary" json:"id"`        // 主键    
    RoleId   int64       `orm:"role_id"    json:"role_id"`   // 角色ID  
    MenuId   int64       `orm:"menu_id"    json:"menu_id"`   // 菜单ID  
    CreateAt *gtime.Time `orm:"create_at"  json:"create_at"` //         
    UpdateAt *gtime.Time `orm:"update_at"  json:"update_at"` //         
}