// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// TbUserRole is the golang structure for table tb_user_role.
type TbUserRole struct {
    Id       uint64      `orm:"id,primary" json:"id"`        // 主键    
    UserId   int64       `orm:"user_id"    json:"user_id"`   // 用户ID  
    RoleId   int64       `orm:"role_id"    json:"role_id"`   // 角色ID  
    CreateAt *gtime.Time `orm:"create_at"  json:"create_at"` //         
    UpdateAt *gtime.Time `orm:"update_at"  json:"update_at"` //         
}