// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rbac/app/dao/internal"
)

// tbMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type tbMenuDao struct {
	*internal.TbMenuDao
}

var (
	// TbMenu is globally public accessible object for table tb_menu operations.
	TbMenu = &tbMenuDao{
		internal.TbMenu,
	}
)

// Fill with you ideas below.