// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rbac/app/dao/internal"
)

// tbRoleMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type tbRoleMenuDao struct {
	*internal.TbRoleMenuDao
}

var (
	// TbRoleMenu is globally public accessible object for table tb_role_menu operations.
	TbRoleMenu = &tbRoleMenuDao{
		internal.TbRoleMenu,
	}
)

// Fill with you ideas below.