// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rbac/app/dao/internal"
)

// tbUserRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type tbUserRoleDao struct {
	*internal.TbUserRoleDao
}

var (
	// TbUserRole is globally public accessible object for table tb_user_role operations.
	TbUserRole = &tbUserRoleDao{
		internal.TbUserRole,
	}
)

// Fill with you ideas below.