// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rbac/app/dao/internal"
)

// tbUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type tbUserDao struct {
	*internal.TbUserDao
}

var (
	// TbUser is globally public accessible object for table tb_user operations.
	TbUser = &tbUserDao{
		internal.TbUser,
	}
)

// Fill with you ideas below.